import { Component } from '@angular/core';
import { DatabaseService } from '../database.service';

@Component({
  selector: 'app-preferencias',
  templateUrl: './preferencias.component.html',
  styleUrls: ['./preferencias.component.css']
})
export class PreferenciasComponent {
  opciones: string[] = [
    'Abandono-posgrado',
    'Administracion_centralud',
    'Admitidos2020-1',
    'Admitidos2023-1',
    'Alertas-seguridad',
    'Apea-admitidos',
    'Apoyoalimentario',
    'Asambleauniversitaria',
    'Carnetdigital',
    'Comunicadosidexud',
    'Concejalesbogota',
    'Contratistas-rh',
    'Convocatoriaequipos',
    'Cps-medioamb',
    'Cuenta-correo-dependencias',
    'Cuenta-google-egresado',
    'Cuenta-inst-egresado',
    'Delegadoscentrorelevo',
    'Docentes-asab-2020',
    'Docentesevaluacion',
    'Egresados-ciencias',
    'Egresados-esp-avaluos',
    'Egresados-esp-bioingenieria',
    'Egresados-esp-gestionproyectos',
    'Egresados-esp-infor',
    'Egresados-esp-ingsoftware',
    'Egresados-esp-proyinformaticos',
    'Egresados-esp-saludocupacional',
    'Egresados-esp-sisgeo',
    'Egresados-esp-telecommoviles',
    'Egresados-esp-teleinfo',
    'Egresados-ing-ambiental',
    'Egresados-ing-catastral',
    'Egresados-ing-electrica',
    'Egresados-ing-electronica',
    'Egresados-ing-industrial',
    'Egresados-ing-sistemas',
    'Egresados-ingenieria',
    'Egresados-medioamb',
    'Egresados-mt-ingenieria',
    'Egresados-mt-ingindustrial',
    'Egresados-mt-moviles',
    'Egresados-mt-teleinformatica',
    'Egresados-sin-vinculo-laboral',
    'Encuestaequipos',
    'Est-admambiental',
    'Est-admdeportiva',
    'Est-danza-2020',
    'Est-escenicas-2020',
    'Est-esp-ambiente',
    'Est-esp-avaluos',
    'Est-esp-bioingenieria',
    'Est-esp-gestionproyectos',
    'Est-esp-infor',
    'Est-esp-ingsoftware',
    'Est-esp-proyinformaticos',
    'Est-esp-recursosnaturales',
    'Est-esp-saludocupacional',
    'Est-esp-sisgeo',
    'Est-esp-telecommoviles',
    'Est-esp-teleinfo',
    'Est-evaluaciondocente',
    'Est-facultad-asab-2017-3',
    'Est-facultad-porvenir',
    'Est-facultad-vivero',
    'Est-ing-ambiental',
    'Est-ing-catastral',
    'Est-ing-civil',
    'Est-ing-control',
    'Est-ing-electrica',
    'Est-ing-electronica',
    'Est-ing-forestal',
    'Est-ing-industrial',
    'Est-ing-sanitaria',
    'Est-ing-sistemas',
    'Est-ing-topo',
    'Est-mt-bosques',
    'Est-mt-desarrollosustentable',
    'Est-mt-ingenieria',
    'Est-mt-ingindustrial',
    'Est-mt-moviles',
    'Est-mt-teleinformatica',
    'Est-musica-2020',
    'Est-plasticas-2020',
    'Est-posgrados-medioamb',
    'Est-tec-civiles',
    'Est-tec-electronica',
    'Est-tec-gesambiental',
    'Est-tec-levtopo',
    'Est-tec-sanea',
    'Est-tec-tecmecanica',
    'Est-tec-telecomunicaciones',
    'Estudiantes-apv',
    'Estudiantes-asab-2020',
    'Estudiantes-ingmecanica',
    'Estudiantes-tecmecanica',
    'Graduacion-oportuna',
    'Gsti',
    'Ilud',
    'Induccion',
    'Ing-control-automatizacion',
    'Ing-telecomunicaciones',
    'Ingenieriacivil',
    'Jurados-votacion-2023',
    'Juradoshcatedra',
    'Lista_getic_idexud',
    'Lista_idexud',
    'Migracionud',
    'Oficinaegresados',
    'Paz-ud',
    'Pcad',
    'Pdi',
    'Pdi-admitidos',
    'Pfisicaoapc',
    'Planta-medioamb',
    'Postgrados-ing',
    'Primersemestre-personales-2020-3',
    'Primersemestre-ud-2020-3',
    'Primersemestre2020-1',
    'Primersemestre2020-3',
    'Pro-esp-recursosnaturales',
    'Prof-admambiental',
    'Prof-admdeportiva',
    'Prof-esp-ambiente',
    'Prof-esp-vias',
    'Prof-ing-ambiental',
    'Prof-ing-forestal',
    'Prof-ing-sanitaria',
    'Prof-ing-topo',
    'Prof-mt-bosques',
    'Prof-mt-desarrollosustentable',
    'Prof-tec-gesambiental',
    'Prof-tec-levtopo',
    'Prof-tec-sanea',
    'Profesores-apv',
    'Profesores-planta',
    'Profesores-vicerrecacad',
    'Prog-egresados',
    'Proyectoscurriculares',
    'Prueba',
    'Rita',
    'Tdigital',
    'Tec-elec-industrial',
    'Tec-electronica',
    'Tecciviles',
    'Toficiales',
    'Usuariosaulastecno',
    'Usuarioswp',
    'Virtualizacionformadoresilud'
  ];

  seleccionados: string[] = [];

  users: any[] = [];

  constructor(private databaseService: DatabaseService) { }

  ngOnInit() {
    this.databaseService.getPreferencias()
      .subscribe(
        users => {
          this.users = users;
          console.log('Preferencias:', users);
        },
        error => {
          console.error('Error getting users:', error);
        }
      );
  }

  guardarPreferencias() {
    console.log('Preferencias seleccionadas:', this.seleccionados);
    // Aquí puedes enviar los datos al backend para guardarlos en la base de datos
  }
}